apiVersion: backstage.io/v1alpha1
kind: Location
metadata:
  name: catalog-locations-psycopg2-lambda-layer
  labels:
    repository: psycopg2-lambda-layer
  annotations:
    github.com/project-slug: orcasecurity/psycopg2-lambda-layer
spec:
  presence: optional
  targets: []
