service: psycopg2-lambda-layer

provider:
  name: aws
  runtime: python3.8
  region: us-gov-west-1
  profile: production-gov
  stage: prod

layers:
  psycopg2-py38:
    description: "psycopg2 python postgresql client library."
    path: layer
    compatibleRuntimes:
      - python3.8
    allowedAccounts:
      - '*'
    retain: true
